version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - shared_uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        # Pass the HF username to the build so the link works correctly
        REACT_APP_HF_USERNAME: ${HUGGING_FACE_USERNAME}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  worker:
    build: ./worker
    volumes:
      - shared_uploads:/app/uploads
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
  shared_uploads: